import type { AnalysisResults, GeneratedRateLimitConfig } from './types';

/**
 * Generates F5 XC JSON config objects from the operator's chosen values.
 */
export function generateConfig(
  lbName: string,
  namespace: string,
  rateLimit: number,
  unit: 'SECOND' | 'MINUTE' | 'HOUR',
  burstMultiplier: number,
  pathRules: Array<{ path: string; method: string; domain: string; limit: number; unit: string }>,
  analysis: AnalysisResults
): GeneratedRateLimitConfig {
  const date = new Date().toISOString().split('T')[0];

  const config: GeneratedRateLimitConfig = {
    rateLimiter: {
      unit,
      total_number: rateLimit,
      burst_multiplier: burstMultiplier,
      period_multiplier: 1,
    },
    rationale: generateRationale(lbName, namespace, rateLimit, unit, burstMultiplier, analysis),
  };

  // Path-specific rules
  if (pathRules.length > 0) {
    const rateLimiterObjects: GeneratedRateLimitConfig['rateLimiterObjects'] = [];

    const rules = pathRules.map((rule, idx) => {
      const rlName = `rl-advisor-${sanitizeName(rule.path)}-${sanitizeName(lbName)}`;

      rateLimiterObjects.push({
        metadata: {
          name: rlName,
          namespace,
          description: `${rule.limit} req/${rule.unit.toLowerCase()} for ${rule.method} ${rule.path}. Generated by Rate Limit Advisor on ${date}.`,
        },
        spec: {
          total_number: rule.limit,
          unit: rule.unit,
          burst_multiplier: 1,
        },
      });

      return {
        metadata: {
          name: `rule-${idx + 1}-${sanitizeName(rule.path)}`,
          disable: false,
        },
        spec: {
          custom_rate_limiter: {
            namespace,
            name: rlName,
            kind: 'rate_limiter' as const,
          },
          any_ip: {} as Record<string, never>,
          any_asn: {} as Record<string, never>,
          any_country: {} as Record<string, never>,
          http_method: {
            methods: [rule.method],
            invert_matcher: false,
          },
          domain_matcher: {
            exact_values: rule.domain ? [rule.domain] : [],
            regex_values: [],
          },
          path: {
            prefix_values: [rule.path],
            exact_values: [],
            regex_values: [],
            suffix_values: [],
            transformers: [],
            invert_matcher: false,
          },
          headers: [],
        },
      };
    });

    config.rateLimiterPolicy = {
      metadata: {
        name: `rl-advisor-${sanitizeName(lbName)}-${date}`,
        namespace,
        description: `Generated by Rate Limit Advisor. Based on 7-day analysis ending ${analysis.analysisEnd}.`,
      },
      spec: { rules },
    };

    config.rateLimiterObjects = rateLimiterObjects;
  }

  return config;
}

function sanitizeName(input: string): string {
  if (!input) return 'unnamed';
  return input
    .replace(/^\//, '')
    .replace(/[^a-z0-9-]/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()
    .slice(0, 30);
}

function generateRationale(
  lbName: string,
  namespace: string,
  _rateLimit: number,
  _unit: string,
  _burstMultiplier: number,
  analysis: AnalysisResults
): string {
  const cleanStats = analysis.rateAnalysis?.clean_only;
  const p99 = cleanStats?.minute?.p99 || 0;
  const p95 = cleanStats?.minute?.p95 || 0;
  const max = cleanStats?.minute?.max || 0;
  const userCount = analysis.userReputationSummary.clean;
  const maliciousCount = analysis.userReputationSummary.malicious;
  const totalLogs = analysis.totalAccessLogs;
  const secEvents = analysis.totalSecurityEvents;
  const startDate = new Date(analysis.analysisStart).toLocaleDateString();
  const endDate = new Date(analysis.analysisEnd).toLocaleDateString();

  let rationale = `Traffic analysis of LB '${lbName}' in namespace '${namespace}' (${startDate} – ${endDate}). ${totalLogs.toLocaleString()} access logs analyzed, ${userCount.toLocaleString()} unique clean users identified.`;

  if (maliciousCount > 0) {
    rationale += ` ${maliciousCount} malicious users excluded (${secEvents.toLocaleString()} security events).`;
  }

  if (analysis.responseBreakdown.origin4xx > 0) {
    rationale += ` ${analysis.responseBreakdown.origin4xx.toLocaleString()} origin-generated 4xx responses included as legitimate traffic.`;
  }

  rationale += ` Key per-user stats: P95=${p95}, P99=${p99}, Max=${max} req/min.`;

  // P99-Burst explanation
  const p99Algo = analysis.algorithms.find(a => a.type === 'p99_burst');
  if (p99Algo) {
    rationale += ` P99-Burst (Recommended): Sets base rate at P99 (${p99}) with safety margin so 99% of users never trigger the limiter. Burst multiplier of ${p99Algo.burstMultiplier}x absorbs the top 1% peaks, giving an effective limit of ${p99Algo.rateLimit * p99Algo.burstMultiplier} req/${p99Algo.granularity}. Best for right-skewed distributions where a few users spike well above the median.`;
  }

  // Peak+Buffer explanation
  const peakAlgo = analysis.algorithms.find(a => a.type === 'peak_buffer');
  if (peakAlgo) {
    rationale += ` Peak + 50%: Uses the highest observed rate (${max} req/min) plus 50% headroom, resulting in ${peakAlgo.rateLimit} req/${peakAlgo.granularity}. A conservative approach that guarantees no legitimate user would have been blocked during the analysis period.`;
  }

  if (analysis.currentConfig.hasRateLimit && analysis.currentConfig.currentLimit) {
    const current = analysis.currentConfig.currentLimit;
    rationale += ` Current configured limit: ${current} req/${analysis.currentConfig.currentUnit?.toLowerCase() || 'minute'}.`;
  }

  return rationale;
}

/**
 * Formats a JSON config object for display with syntax-like presentation.
 */
export function formatConfigJSON(obj: unknown): string {
  return JSON.stringify(obj, null, 2);
}
